Repository garden-co/jazz, pull requests merged in 2025-04, with the labels that each got.

#1786 fix(coValueState): support CoValue re-load after it is marked as unavailable and improve timeout
  .changeset/cyan-eggs-think.md
  packages/cojson/src/coValueState.ts
  packages/cojson/src/sync.ts
  packages/cojson/src/tests/sync.test.ts
Labels: pre-release

#1828 1827 feat: updating design system readme & meta data
  homepage/design-system/README.md
  homepage/design-system/src/app/layout.tsx
Labels: enhancement

#1836 1830 feat: creating opengraph-image.tsx on homepage
  homepage/design-system/src/app/components/atoms/logos/JazzLogo.tsx
  homepage/design-system/src/app/components/organisms/OpenGraphImage.tsx
  homepage/homepage/app/layout.tsx
  homepage/homepage/app/opengraph-image.tsx
  homepage/homepage/components/home/HeroSection.tsx
  homepage/homepage/lib/marketingCopy.ts
  homepage/homepage/public/fonts/Manrope-SemiBold.ttf
  homepage/homepage/public/social-image.png
Labels: feature, enhancement

#1882 fix: handle null properties in the CoMap deep loading
  .changeset/sharp-rules-peel.md
  packages/jazz-tools/src/coValues/deepLoading.ts
  packages/jazz-tools/src/tests/deepLoading.test.ts
Labels: pre-release

#1895 fix(inbox): ensure that the message is fully uploaded before sharing the id with the worker
  packages/jazz-tools/src/coValues/inbox.ts
Labels: pre-release

#1898 fix(inbox): gracefully handle unavailable messages error
  .changeset/rotten-cameras-yell.md
  packages/jazz-tools/src/coValues/inbox.ts
  packages/jazz-tools/src/tests/inbox.test.ts
Labels: pre-release

#1922 1856 - Fix twoslash popup container overflow on hover
  homepage/homepage/app/globals.css
  homepage/homepage/lib/docMdxContent.tsx
Labels: bug, docs

#1901 fix: improve peer reconciliation
  .changeset/smart-ducks-compare.md
  packages/cojson-storage-sqlite/src/tests/messagesTestUtils.ts
  packages/cojson-storage-sqlite/src/tests/sqlite.test.ts
  packages/cojson-storage-sqlite/src/tests/testUtils.ts
  packages/cojson/src/PeerState.ts
  packages/cojson/src/sync.ts
  packages/cojson/src/tests/SyncStateManager.test.ts
  packages/cojson/src/tests/group.test.ts
  packages/cojson/src/tests/messagesTestUtils.ts
  packages/cojson/src/tests/sync.load.test.ts
  packages/cojson/src/tests/sync.peerReconciliation.test.ts
  packages/cojson/src/tests/sync.test.ts
  packages/cojson/src/tests/testUtils.ts
  packages/jazz-tools/src/coValues/account.ts
  packages/jazz-tools/src/tests/groupsAndAccounts.test.ts
  tests/browser-integration/src/sync.test.ts
  tests/browser-integration/src/syncConflicts.test.ts
  tests/e2e/tests/RetryUnavailable.test.ts
Labels: pre-release

#1947 fix: remove risky awaits from handleSyncMessage code path
  .changeset/poor-deers-hammer.md
  packages/cojson/src/sync.ts
  packages/cojson/src/tests/sync.load.test.ts
  packages/cojson/src/tests/sync.mesh.test.ts
  packages/cojson/src/tests/sync.peerReconciliation.test.ts
  packages/cojson/src/tests/sync.storage.test.ts
  packages/cojson/src/tests/sync.upload.test.ts
  packages/jazz-tools/src/tests/groupsAndAccounts.test.ts
Labels: pre-release

#1951 fix: skip loading from closed peers and add a timeout on the addPeer wait
  .changeset/strange-wolves-watch.md
  packages/cojson/src/PeerState.ts
  packages/cojson/src/coValueState.ts
  packages/cojson/src/sync.ts
  packages/cojson/src/tests/sync.load.test.ts
Labels: pre-release

#1972 fix: do not crash when loading a CoValue core without the group in the sync server
  .changeset/proud-rocks-punch.md
  packages/cojson/src/coValueCore.ts
  packages/cojson/src/tests/coValueCore.test.ts
Labels: pre-release

#2005 feat(sync): make the incoming messages handling in the sync manager syncronous
  .changeset/long-rabbits-kick.md
  packages/cojson-storage-sqlite/src/tests/sqlite.test.ts
  packages/cojson/src/PeerState.ts
  packages/cojson/src/PriorityBasedMessageQueue.ts
  packages/cojson/src/coValueState.ts
  packages/cojson/src/sync.ts
  packages/cojson/src/tests/PeerState.test.ts
  packages/cojson/src/tests/PriorityBasedMessageQueue.test.ts
  packages/cojson/src/tests/SyncStateManager.test.ts
  packages/cojson/src/tests/sync.load.test.ts
  packages/cojson/src/tests/sync.mesh.test.ts
  packages/cojson/src/tests/sync.peerReconciliation.test.ts
  packages/cojson/src/tests/sync.storage.test.ts
  packages/cojson/src/tests/sync.upload.test.ts
  packages/cojson/src/tests/testUtils.ts
Labels: pre-release

#2056 2049-show-how-to-supply-owner-in-filestream-docs
  homepage/homepage/content/docs/using-covalues/filestreams.mdx
Labels: docs
