Repository garden-co/jazz, pull requests merged in 2025-02, with the labels that each got.

#1305 feat: remove the ws dependency and use native WebSocket
  .changeset/purple-eagles-cover.md
  packages/jazz-nodejs/package.json
  packages/jazz-nodejs/src/index.ts
  packages/jazz-nodejs/src/test/webSocketWithReconnection.test.ts
  packages/jazz-nodejs/src/webSocketWithReconnection.ts
  pnpm-lock.yaml
Labels: breaking change

#1366 fix: correctly setup the metro config on React Native templates
  .changeset/red-geese-rescue.md
  packages/create-jazz-app/src/config.ts
  packages/create-jazz-app/src/index.ts
Labels: pre-release

#1403 fix: fixes clerk auth flow
  .changeset/spotty-shoes-play.md
  packages/jazz-auth-clerk/src/index.ts
  packages/jazz-auth-clerk/src/tests/types.test.ts
  packages/jazz-auth-clerk/src/types.ts
  packages/jazz-browser/src/BrowserContextManager.ts
  packages/jazz-browser/src/index.ts
  packages/jazz-react-auth-clerk/package.json
  packages/jazz-react-auth-clerk/src/index.tsx
  packages/jazz-react-auth-clerk/src/tests/JazzProviderWithClerk.test.tsx
  packages/jazz-react/src/provider.tsx
  packages/jazz-tools/src/implementation/ContextManager.ts
  pnpm-lock.yaml
Labels: pre-release

#1413 Bumps crypto version
  .changeset/fuzzy-carpets-beg.md
  packages/cojson/package.json
  packages/cojson/src/crypto/WasmCrypto.ts
  pnpm-lock.yaml
Labels: pre-release

#1467 feat: return inherited members and add getRoleOf and hasPermissions methods to Group
  .changeset/cuddly-paws-kiss.md
  .changeset/eight-dingos-retire.md
  packages/cojson/src/coValues/group.ts
  packages/jazz-tools/src/coValues/account.ts
  packages/jazz-tools/src/coValues/group.ts
  packages/jazz-tools/src/tests/groupsAndAccounts.test.ts
Labels: breaking change, pre-release

#1487 fix(PasskeyAuth): set name iff username given
  .changeset/six-lizards-sip.md
  packages/jazz-browser/src/auth/PasskeyAuth.ts
  packages/jazz-browser/src/tests/PasskeyAuth.test.ts
Labels: bug, good first issue, breaking change

#1519 fix(create-jazz-app): handle workspace devDependencies
  .changeset/rude-bananas-end.md
  packages/create-jazz-app/src/index.ts
Labels: pre-release

#1507 feat(PasskeyAuth): support random passphrase generation
  .changeset/khaki-rockets-sort.md
  examples/passphrase/src/index.css
  examples/passphrase/src/main.tsx
  packages/jazz-react-core/src/auth/PassphraseAuth.tsx
  packages/jazz-svelte/src/lib/auth/PassphraseAuth.svelte.ts
  packages/jazz-tools/src/auth/PassphraseAuth.ts
  packages/jazz-tools/src/implementation/ContextManager.ts
  packages/jazz-tools/src/tests/ContextManager.test.ts
  packages/jazz-tools/src/tests/PassphraseAuth.test.ts
  packages/jazz-tools/src/types.ts
  packages/jazz-vue/src/auth/usePassphraseAuth.ts
Labels: pre-release

#1493 Cursor rules with create-jazz-app
  .changeset/selfish-guests-promise.md
  .github/workflows/pre-release.yml
  packages/create-jazz-app/src/index.ts
Labels: pre-release
