Repository garden-co/jazz, pull requests merged in 2025-03, with the labels that each got.

#1512 feat!(Groups): API to unextend group
  .changeset/perfect-students-rhyme.md
  examples/music-player/src/4_actions.ts
  examples/music-player/src/components/MusicTrackRow.tsx
  examples/music-player/tests/createAndShare.spec.ts
  examples/music-player/tests/pages/HomePage.ts
  packages/cojson/src/coValues/group.ts
  packages/cojson/src/tests/group.test.ts
  packages/cojson/src/tests/permissions.test.ts
  packages/jazz-tools/src/coValues/group.ts
Labels: good first issue, feature, enhancement

#1650 fix: use PureJSCrypto as fallback when WasmCrypto fails to initialize
  .changeset/tiny-ladybugs-laugh.md
  packages/cojson-transport-ws/src/tests/integration.test.ts
  packages/cojson/src/crypto/WasmCrypto.ts
  packages/jazz-tools/src/tests/schemaUnion.test.ts
  tests/cloudflare-workers/src/index.ts
Labels: pre-release

#1585 1572-filestream-docs
  homepage/homepage/app/(docs)/docs/[framework]/[...slug]/using-covalues/filestreams.mdx
  homepage/homepage/app/(docs)/docs/[framework]/[...slug]/using-covalues/imagedef.mdx
  homepage/homepage/app/(docs)/docs/[framework]/[...slug]/using-covalues/imagedef/react-native.mdx
  homepage/homepage/app/(docs)/docs/[framework]/[...slug]/using-covalues/imagedef/react.mdx
  homepage/homepage/lib/docNavigationItems.js
  packages/jazz-tools/src/coValues/extensions/imageDef.ts
  packages/jazz-tools/src/tests/coFeed.test.ts
  packages/jazz-tools/src/tests/imageDef.test.ts
Labels: dx

#1471 jazz-739-handle-reloading-page-while-image-upload-is-in-progress
  .changeset/healthy-peas-kick.md
  .changeset/twenty-humans-sort.md
  examples/image-upload/package.json
  examples/image-upload/postcss.config.js
  examples/image-upload/src/App.tsx
  examples/image-upload/src/ImageUpload.tsx
  examples/image-upload/src/index.css
  examples/image-upload/tailwind.config.ts
  packages/cojson/src/coValueCore.ts
  packages/cojson/src/coValues/coStream.ts
  packages/cojson/src/tests/coStream.test.ts
  packages/jazz-browser-media-images/src/index.ts
  pnpm-lock.yaml
  tests/browser-integration/package.json
  tests/browser-integration/src/fixtures/jazz-logo.png
  tests/browser-integration/src/images.test.ts
Labels: user-experience

#1734 perf: optimize Group.roleOf getter and made the transactions validation incremental for CoMap and CoFeed
  .changeset/giant-mails-sneeze.md
  packages/cojson/src/coValueCore.ts
  packages/cojson/src/coValues/coMap.ts
  packages/cojson/src/coValues/coStream.ts
  packages/cojson/src/coValues/group.ts
  packages/cojson/src/permissions.ts
  packages/cojson/src/tests/permissions.test.ts
  packages/jazz-tools/src/coValues/group.ts
Labels: pre-release

#1735 fix: trigger a single update when loading a locally available list of items
  .changeset/fifty-planes-yawn.md
  packages/jazz-react-core/src/tests/useCoState.test.ts
  packages/jazz-tools/src/coValues/interfaces.ts
  packages/jazz-tools/src/implementation/subscriptionScope.ts
  packages/jazz-tools/src/tests/subscribe.test.ts
Labels: pre-release
